# Generated by Django 6.1 on 2026-09-04 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCRAPED', 'Scraped'), ('MATCHED', 'Matched'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('cleaned_text', models.TextField(blank=True, help_text='Cleaned text for AI processing')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('SHORTLISTED', 'Shortlisted'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offer Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DEADLINE_MISSED', 'Deadline Missed'), ('NOT_INTERESTED', 'Not Interested')], default='PENDING_REVIEW', help_text='Application workflow status', max_length=20)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('application_result', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered'), ('WITHDRAWN', 'Withdrawn')], help_text='Final outcome', max_length=20, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('NOT_QUALIFIED', 'Not Qualified'), ('SALARY_MISMATCH', 'Salary Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('DEADLINE_PASSED', 'Deadline Passed'), ('FOUND_BETTER', 'Found Better'), ('OTHER', 'Other')], help_text='Why rejected', max_length=20, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='websites.website')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, help_text='Position title from the advertisement', max_length=500)),
                ('institution', models.CharField(blank=True, help_text='Institution/organization name', max_length=500)),
                ('country', models.CharField(blank=True, help_text='Country where the position is located', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City where the position is located', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Full address of the position')),
                ('position_type', models.CharField(blank=True, help_text='Type of position (e.g., PhD, Postdoc, Faculty)', max_length=100)),
                ('research_area', models.JSONField(blank=True, default=list, help_text='List of research areas mentioned')),
                ('main_research_objective', models.TextField(blank=True, help_text='Main research objective from the position')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='Key topics mentioned in the position')),
                ('research_methods', models.JSONField(blank=True, default=list, help_text='Research methods mentioned in the position')),
                ('target_application_domain', models.JSONField(blank=True, default=list, help_text='Target application domains')),
                ('required_background', models.JSONField(blank=True, default=dict, help_text='Required background with mandatory/core/preferred')),
                ('required_skills', models.JSONField(blank=True, default=dict, help_text='Required skills with mandatory/core/preferred')),
                ('funding_and_duration', models.CharField(blank=True, help_text='Funding information and duration', max_length=500)),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline date (YYYY-MM-DD)', null=True)),
                ('application_deadline_timezone', models.CharField(blank=True, help_text='Timezone of the deadline', max_length=50)),
                ('application_deadline_iso', models.CharField(blank=True, help_text='Full ISO datetime of deadline', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the position (YYYY-MM-DD)', null=True)),
                ('start_date_iso', models.CharField(blank=True, help_text='Full ISO datetime of start date', max_length=50)),
                ('application_url', models.URLField(blank=True, help_text='Direct link to apply', max_length=500)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for inquiries', max_length=200)),
                ('contact_name', models.CharField(blank=True, help_text='Contact person name', max_length=200)),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='List of required application documents')),
                ('education_background', models.TextField(blank=True, help_text="Candidate's education background summary")),
                ('research_background', models.TextField(blank=True, help_text="Candidate's research background summary")),
                ('technical_and_methodological_skills', models.TextField(blank=True, help_text="Candidate's technical skills")),
                ('professional_experience', models.TextField(blank=True, help_text="Candidate's professional experience")),
                ('publication_and_academic_record', models.TextField(blank=True, help_text="Candidate's publication and academic record")),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('eligibility_score', models.FloatField(default=0.0, help_text='Eligibility score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('academic_fit_score', models.FloatField(default=0.0, help_text='Academic fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_fit_score', models.FloatField(default=0.0, help_text='Research fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_methodological_fit_score', models.FloatField(default=0.0, help_text='Technical and methodological fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('domain_fit_score', models.FloatField(default=0.0, help_text='Domain fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_experience_score', models.FloatField(default=0.0, help_text='Research experience score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competitiveness_score', models.FloatField(default=0.0, help_text='Competitiveness score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_dimensions', models.JSONField(blank=True, default=dict, help_text='Weighted dimension scores')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence of matches and gaps')),
                ('match_category', models.CharField(choices=[('excellent_match', 'Excellent Match'), ('good_match', 'Good Match'), ('possible_match', 'Possible Match'), ('weak_match', 'Weak Match'), ('error', 'Error')], default='weak_match', help_text='Match category from final verdict', max_length=50)),
                ('application_recommendation', models.CharField(blank=True, choices=[('strongly_recommended', 'Strongly Recommended'), ('recommended', 'Recommended'), ('possible_but_risky', 'Possible but Risky'), ('not_recommended', 'Not Recommended')], help_text='Application recommendation', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Summary of the match assessment')),
                ('main_reason', models.TextField(blank=True, help_text='Main reason for the match verdict')),
                ('prompt_id', models.IntegerField(blank=True, help_text='ID of the prompt template used', null=True)),
                ('prompt_name', models.CharField(blank=True, help_text='Name of the prompt template used', max_length=200)),
                ('prompt_version', models.CharField(blank=True, help_text='Version of the prompt template used', max_length=50)),
                ('language', models.CharField(default='English', help_text='Language used for the match', max_length=50)),
                ('raw_response', models.TextField(blank=True, help_text='Raw AI response (for debugging)')),
                ('full_json_response', models.JSONField(blank=True, default=dict, help_text='Complete JSON response from AI')),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When the match was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the match was last updated')),
                ('position', models.OneToOneField(help_text='The position this match belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='positions.position')),
            ],
            options={
                'verbose_name': 'Position Match',
                'verbose_name_plural': 'Position Matches',
                'ordering': ['-overall_score', '-matched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['status', 'scraped_at'], name='positions_p_status_74190c_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['website', 'url'], name='positions_p_website_33c9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['application_status'], name='positions_p_applica_0e94a4_idx'),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['overall_score'], name='positions_p_overall_c1cce3_idx'),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['match_category'], name='positions_p_match_c_848df5_idx'),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['position', 'overall_score'], name='positions_p_positio_11784e_idx'),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['confidence'], name='positions_p_confide_087631_idx'),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['application_deadline'], name='positions_p_applica_ea124a_idx'),
        ),
    ]
