# Generated by Django 6.1 on 2026-08-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCRAPED', 'Scraped'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='websites.website')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['status', 'scraped_at'], name='positions_p_status_74190c_idx'), models.Index(fields=['website', 'url'], name='positions_p_website_33c9e8_idx')],
            },
        ),
    ]
