# Generated by Django 6.1 on 2026-08-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cleaned_text',
            field=models.TextField(blank=True, help_text='Cleaned text for AI processing'),
        ),
    ]
