# Generated by Django 6.1 on 2026-08-10 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_position_cleaned_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, help_text='Position title from the advertisement', max_length=500)),
                ('institution', models.CharField(blank=True, help_text='Institution/organization name', max_length=500)),
                ('country', models.CharField(blank=True, help_text='Country where the position is located', max_length=100)),
                ('position_type', models.CharField(blank=True, help_text='Type of position (e.g., PhD, Postdoc, Faculty)', max_length=100)),
                ('research_area', models.JSONField(blank=True, default=list, help_text='List of research areas mentioned')),
                ('main_research_objective', models.TextField(blank=True, help_text='Main research objective from the position')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='Key topics mentioned in the position')),
                ('required_background', models.JSONField(blank=True, default=list, help_text='Required background qualifications')),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='Required skills for the position')),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text='Preferred skills (nice to have)')),
                ('funding_and_duration', models.CharField(blank=True, help_text='Funding information and duration', max_length=500)),
                ('education_background', models.TextField(blank=True, help_text="Candidate's education background summary")),
                ('research_background', models.TextField(blank=True, help_text="Candidate's research background summary")),
                ('technical_and_methodological_skills', models.TextField(blank=True, help_text="Candidate's technical skills")),
                ('professional_experience', models.TextField(blank=True, help_text="Candidate's professional experience")),
                ('publication_and_academic_record', models.TextField(blank=True, help_text="Candidate's publication and academic record")),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Confidence level of the match assessment', max_length=20)),
                ('academic_fit_score', models.FloatField(default=0.0, help_text='Academic fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('research_fit_score', models.FloatField(default=0.0, help_text='Research fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competitiveness_score', models.FloatField(default=0.0, help_text='Competitiveness score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_category', models.CharField(choices=[('excellent_match', 'Excellent Match'), ('good_match', 'Good Match'), ('possible_match', 'Possible Match'), ('weak_match', 'Weak Match'), ('error', 'Error')], default='weak_match', help_text='Match category from final verdict', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Summary of the match assessment')),
                ('main_reason', models.TextField(blank=True, help_text='Main reason for the match verdict')),
                ('prompt_id', models.IntegerField(blank=True, help_text='ID of the prompt template used', null=True)),
                ('prompt_name', models.CharField(blank=True, help_text='Name of the prompt template used', max_length=200)),
                ('prompt_version', models.CharField(blank=True, help_text='Version of the prompt template used', max_length=50)),
                ('language', models.CharField(default='English', help_text='Language used for the match', max_length=50)),
                ('raw_response', models.TextField(blank=True, help_text='Raw AI response (for debugging)')),
                ('full_json_response', models.JSONField(blank=True, default=dict, help_text='Complete JSON response from AI')),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When the match was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the match was last updated')),
                ('position', models.OneToOneField(help_text='The position this match belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='positions.position')),
            ],
            options={
                'verbose_name': 'Position Match',
                'verbose_name_plural': 'Position Matches',
                'ordering': ['-overall_score', '-matched_at'],
                'indexes': [models.Index(fields=['overall_score'], name='positions_p_overall_c1cce3_idx'), models.Index(fields=['match_category'], name='positions_p_match_c_848df5_idx'), models.Index(fields=['position', 'overall_score'], name='positions_p_positio_11784e_idx'), models.Index(fields=['confidence'], name='positions_p_confide_087631_idx')],
            },
        ),
    ]
