# Generated by Django 6.1 on 2026-08-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_positionmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmatch',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the position'),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Application deadline date (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='application_deadline_iso',
            field=models.CharField(blank=True, help_text='Full ISO datetime of deadline', max_length=50),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='application_deadline_timezone',
            field=models.CharField(blank=True, help_text='Timezone of the deadline', max_length=50),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='application_url',
            field=models.URLField(blank=True, help_text='Direct link to apply', max_length=500),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='city',
            field=models.CharField(blank=True, help_text='City where the position is located', max_length=100),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for inquiries', max_length=200),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=200),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required application documents'),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the position (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='start_date_iso',
            field=models.CharField(blank=True, help_text='Full ISO datetime of start date', max_length=50),
        ),
        migrations.AddIndex(
            model_name='positionmatch',
            index=models.Index(fields=['application_deadline'], name='positions_p_applica_ea124a_idx'),
        ),
    ]
