# Generated by Django 6.1 on 2026-08-10 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_positionmatch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionmatch',
            name='preferred_skills',
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='application_recommendation',
            field=models.CharField(blank=True, choices=[('strongly_recommended', 'Strongly Recommended'), ('recommended', 'Recommended'), ('possible_but_risky', 'Possible but Risky'), ('not_recommended', 'Not Recommended')], help_text='Application recommendation', max_length=50),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='domain_fit_score',
            field=models.FloatField(default=0.0, help_text='Domain fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='eligibility_score',
            field=models.FloatField(default=0.0, help_text='Eligibility score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Evidence of matches and gaps'),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='research_experience_score',
            field=models.FloatField(default=0.0, help_text='Research experience score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='research_methods',
            field=models.JSONField(blank=True, default=list, help_text='Research methods mentioned in the position'),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='target_application_domain',
            field=models.JSONField(blank=True, default=list, help_text='Target application domains'),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='technical_methodological_fit_score',
            field=models.FloatField(default=0.0, help_text='Technical and methodological fit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='positionmatch',
            name='weighted_dimensions',
            field=models.JSONField(blank=True, default=dict, help_text='Weighted dimension scores'),
        ),
        migrations.AlterField(
            model_name='positionmatch',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='positionmatch',
            name='required_background',
            field=models.JSONField(blank=True, default=dict, help_text='Required background with mandatory/core/preferred'),
        ),
        migrations.AlterField(
            model_name='positionmatch',
            name='required_skills',
            field=models.JSONField(blank=True, default=dict, help_text='Required skills with mandatory/core/preferred'),
        ),
    ]
