# Generated by Django 6.1 on 2026-08-10 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the website', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the website')),
                ('base_url', models.URLField(help_text='Base URL of the website', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('pagination_url_pattern', models.CharField(help_text='URL pattern with {page} placeholder', max_length=500)),
                ('listing_item_selector', models.CharField(help_text="CSS selector for each position container (e.g., '.job-list-item', '.job-card')", max_length=500)),
                ('position_link_selector', models.CharField(help_text="CSS selector for position link within the container (e.g., 'a.job-link', '.title a')", max_length=500)),
                ('position_title_selector', models.CharField(blank=True, help_text="CSS selector for position title within the container (e.g., 'h4', '.job-title')", max_length=500)),
                ('position_company_selector', models.CharField(blank=True, help_text="CSS selector for company name within the container (e.g., '.company', '.employer')", max_length=500)),
                ('detail_container_selector', models.CharField(help_text='CSS selector for detail container', max_length=500)),
                ('max_pages', models.IntegerField(default=0, help_text='Maximum pages to scrape per run - 0: Unlimited')),
                ('request_timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('request_delay', models.FloatField(default=1.0, help_text='Delay between requests in seconds')),
                ('user_agent', models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36', help_text='User agent string', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this website is active for scraping')),
                ('is_enabled', models.BooleanField(default=True, help_text='Alias for is_active')),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful scrape', null=True)),
                ('last_scrape_count', models.IntegerField(default=0, help_text='Number of positions scraped in the last run')),
                ('total_scraped_count', models.IntegerField(default=0, help_text='Total number of positions scraped from this website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='websites_we_is_acti_e458bc_idx'), models.Index(fields=['last_scraped_at'], name='websites_we_last_sc_e2df76_idx'), models.Index(fields=['name', 'is_active'], name='websites_we_name_e388dd_idx')],
            },
        ),
    ]
