# Generated by Django 6.1 on 2026-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='api_auth_token',
            field=models.CharField(blank=True, help_text='Bearer token or API key for authentication (if required)', max_length=500),
        ),
        migrations.AddField(
            model_name='website',
            name='api_count_key',
            field=models.CharField(blank=True, help_text='JSON key for the total count of items (if provided)', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Full API endpoint URL (e.g., https://api.example.com/v1/jobs/)', max_length=500),
        ),
        migrations.AddField(
            model_name='website',
            name='api_extra_params',
            field=models.JSONField(blank=True, default=dict, help_text="Additional static query parameters as a JSON object, e.g., {'boost_spotlights': True, 'is_active': True}"),
        ),
        migrations.AddField(
            model_name='website',
            name='api_item_company_key',
            field=models.CharField(blank=True, help_text="JSON key for the company/organization (e.g., 'organisation_name', 'subline')", max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_item_description_key',
            field=models.CharField(blank=True, help_text='JSON key for the description/cleaned text (if included in listing)', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_item_title_key',
            field=models.CharField(blank=True, help_text="JSON key for the position title (e.g., 'title', 'headline')", max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_item_url_key',
            field=models.CharField(blank=True, help_text="JSON key for the position URL (e.g., 'absolute_url', 'link.url')", max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_limit_param',
            field=models.CharField(blank=True, default='limit', help_text="Query parameter name for items per page (e.g., 'limit', 'per_page')", max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='api_next_key',
            field=models.CharField(blank=True, help_text='JSON key for the next page URL (if provided by the API)', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='api_pagination_param',
            field=models.CharField(blank=True, default='page', help_text="Query parameter name for page number (e.g., 'page', 'offset')", max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='api_results_key',
            field=models.CharField(blank=True, default='results', help_text="JSON key where the list of items is located (e.g., 'results', 'data.items')", max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='scraping_method',
            field=models.CharField(choices=[('html', 'HTML Scraping'), ('api', 'API Scraping')], default='html', help_text='Select whether to scrape HTML pages or use a JSON API.', max_length=10),
        ),
    ]
