# Generated by Django 6.1 on 2026-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_api_auth_token_website_api_count_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='detail_container_selector',
            field=models.CharField(blank=True, help_text='CSS selector for detail container', max_length=500),
        ),
        migrations.AlterField(
            model_name='website',
            name='listing_item_selector',
            field=models.CharField(blank=True, help_text="CSS selector for each position container (e.g., '.job-list-item', '.job-card')", max_length=500),
        ),
        migrations.AlterField(
            model_name='website',
            name='position_link_selector',
            field=models.CharField(blank=True, help_text="CSS selector for position link within the container (e.g., 'a.job-link', '.title a')", max_length=500),
        ),
    ]
