# Generated by Django 6.1 on 2026-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_alter_website_detail_container_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='api_detail_key',
            field=models.CharField(blank=True, help_text='JSON key for the full description/cleaned text in the API detail response. If blank, falls back to api_item_description_key from listing.', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='detail_source',
            field=models.CharField(choices=[('html', 'HTML Scraping'), ('api', 'API Scraping')], default='html', max_length=10),
        ),
    ]
