# Generated by Django 6.1 on 2026-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_website_api_detail_key_website_detail_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='detail_api_endpoint',
            field=models.URLField(blank=True, help_text='Detail API endpoint URL (e.g., https://api.example.com/v1/jobs/)', max_length=500),
        ),
    ]
