# Generated by Django 6.1 on 2026-08-19 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_website_detail_api_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL of the website', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='website',
            name='pagination_url_pattern',
            field=models.CharField(blank=True, help_text='URL pattern with {page} placeholder', max_length=500),
        ),
    ]
