# Generated by Django 6.1 on 2026-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name to identify this prompt template', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this prompt is optimized for')),
                ('template', models.TextField(help_text='The prompt template with placeholders: {cv}, {position}, {language}, {json_structure}')),
                ('default_language', models.CharField(default='English', help_text='Default language for responses', max_length=50)),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version of this prompt', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Is this the currently active prompt? Only one can be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this prompt was last activated', null=True)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='ai_promptte_is_acti_c9b4f2_idx'), models.Index(fields=['name', 'version'], name='ai_promptte_name_9702d7_idx')],
            },
        ),
    ]
